# Generated by Django 5.2.12 on 2026-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='cv_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='screening_mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('meet', 'Meet')], default='chat', max_length=10),
        ),
    ]
