# Generated by Django 5.2.12 on 2026-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0005_vacancy_archived_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
