# Generated by Django 5.2.12 on 2026-03-22 12:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_company_subscription_plan"),
        ("vacancies", "0008_vacancy_keywords_search_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerCompany",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255)),
                ("logo", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("file", "File"), ("website", "Website")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="employers", to="accounts.company"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="vacancy",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vacancies",
                to="vacancies.employercompany",
            ),
        ),
    ]
