# Generated by Django 5.2.12 on 2026-03-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_seed_countries"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "industries",
                "ordering": ["name"],
            },
        ),
    ]
