# Generated by Django 5.2.12 on 2026-03-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_seed_industries"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("slug", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
