from django.db import migrations


def seed_skills(apps, schema_editor):
    Skill = apps.get_model("common", "Skill")
    skills = [
        ("python", "Python", "programming"),
        ("javascript", "JavaScript", "programming"),
        ("typescript", "TypeScript", "programming"),
        ("java", "Java", "programming"),
        ("csharp", "C#", "programming"),
        ("cpp", "C++", "programming"),
        ("c", "C", "programming"),
        ("go", "Go", "programming"),
        ("rust", "Rust", "programming"),
        ("ruby", "Ruby", "programming"),
        ("php", "PHP", "programming"),
        ("swift", "Swift", "programming"),
        ("kotlin", "Kotlin", "programming"),
        ("scala", "Scala", "programming"),
        ("r", "R", "programming"),
        ("dart", "Dart", "programming"),
        ("sql", "SQL", "programming"),
        ("bash", "Bash / Shell", "programming"),
        ("html-css", "HTML / CSS", "programming"),
        ("solidity", "Solidity", "programming"),
        ("react", "React", "framework"),
        ("vue", "Vue.js", "framework"),
        ("angular", "Angular", "framework"),
        ("nextjs", "Next.js", "framework"),
        ("nuxtjs", "Nuxt.js", "framework"),
        ("svelte", "Svelte", "framework"),
        ("django", "Django", "framework"),
        ("flask", "Flask", "framework"),
        ("fastapi", "FastAPI", "framework"),
        ("spring", "Spring Boot", "framework"),
        ("express", "Express.js", "framework"),
        ("nestjs", "NestJS", "framework"),
        ("rails", "Ruby on Rails", "framework"),
        ("laravel", "Laravel", "framework"),
        ("dotnet", ".NET", "framework"),
        ("flutter", "Flutter", "framework"),
        ("react-native", "React Native", "framework"),
        ("tailwindcss", "Tailwind CSS", "framework"),
        ("bootstrap", "Bootstrap", "framework"),
        ("jquery", "jQuery", "framework"),
        ("postgresql", "PostgreSQL", "database"),
        ("mysql", "MySQL", "database"),
        ("mongodb", "MongoDB", "database"),
        ("redis", "Redis", "database"),
        ("elasticsearch", "Elasticsearch", "database"),
        ("sqlite", "SQLite", "database"),
        ("mssql", "Microsoft SQL Server", "database"),
        ("oracle-db", "Oracle Database", "database"),
        ("cassandra", "Cassandra", "database"),
        ("dynamodb", "DynamoDB", "database"),
        ("firebase", "Firebase", "database"),
        ("aws", "AWS", "cloud"),
        ("gcp", "Google Cloud", "cloud"),
        ("azure", "Microsoft Azure", "cloud"),
        ("docker", "Docker", "cloud"),
        ("kubernetes", "Kubernetes", "cloud"),
        ("terraform", "Terraform", "cloud"),
        ("ansible", "Ansible", "cloud"),
        ("jenkins", "Jenkins", "cloud"),
        ("github-actions", "GitHub Actions", "cloud"),
        ("gitlab-ci", "GitLab CI/CD", "cloud"),
        ("nginx", "Nginx", "cloud"),
        ("linux", "Linux", "cloud"),
        ("ci-cd", "CI/CD", "cloud"),
        ("monitoring", "Monitoring & Observability", "cloud"),
        ("machine-learning", "Machine Learning", "data"),
        ("deep-learning", "Deep Learning", "data"),
        ("nlp", "NLP", "data"),
        ("computer-vision", "Computer Vision", "data"),
        ("data-analysis", "Data Analysis", "data"),
        ("data-engineering", "Data Engineering", "data"),
        ("pandas", "Pandas", "data"),
        ("numpy", "NumPy", "data"),
        ("tensorflow", "TensorFlow", "data"),
        ("pytorch", "PyTorch", "data"),
        ("power-bi", "Power BI", "data"),
        ("tableau", "Tableau", "data"),
        ("apache-spark", "Apache Spark", "data"),
        ("etl", "ETL Pipelines", "data"),
        ("llm", "LLM / GenAI", "data"),
        ("git", "Git", "tool"),
        ("jira", "Jira", "tool"),
        ("confluence", "Confluence", "tool"),
        ("figma", "Figma", "tool"),
        ("postman", "Postman", "tool"),
        ("vscode", "VS Code", "tool"),
        ("intellij", "IntelliJ IDEA", "tool"),
        ("slack", "Slack", "tool"),
        ("notion", "Notion", "tool"),
        ("trello", "Trello", "tool"),
        ("leadership", "Leadership", "soft"),
        ("communication", "Communication", "soft"),
        ("teamwork", "Teamwork", "soft"),
        ("problem-solving", "Problem Solving", "soft"),
        ("critical-thinking", "Critical Thinking", "soft"),
        ("time-management", "Time Management", "soft"),
        ("adaptability", "Adaptability", "soft"),
        ("creativity", "Creativity", "soft"),
        ("negotiation", "Negotiation", "soft"),
        ("presentation", "Presentation Skills", "soft"),
        ("mentoring", "Mentoring", "soft"),
        ("conflict-resolution", "Conflict Resolution", "soft"),
        ("project-management", "Project Management", "business"),
        ("product-management", "Product Management", "business"),
        ("agile", "Agile / Scrum", "business"),
        ("kanban", "Kanban", "business"),
        ("business-analysis", "Business Analysis", "business"),
        ("strategic-planning", "Strategic Planning", "business"),
        ("budgeting", "Budgeting & Finance", "business"),
        ("stakeholder-management", "Stakeholder Management", "business"),
        ("risk-management", "Risk Management", "business"),
        ("crm", "CRM", "business"),
        ("erp", "ERP Systems", "business"),
        ("ui-design", "UI Design", "design"),
        ("ux-design", "UX Design", "design"),
        ("graphic-design", "Graphic Design", "design"),
        ("prototyping", "Prototyping", "design"),
        ("adobe-photoshop", "Adobe Photoshop", "design"),
        ("adobe-illustrator", "Adobe Illustrator", "design"),
        ("sketch", "Sketch", "design"),
        ("wireframing", "Wireframing", "design"),
        ("seo", "SEO", "marketing"),
        ("sem", "SEM / PPC", "marketing"),
        ("content-marketing", "Content Marketing", "marketing"),
        ("social-media", "Social Media Marketing", "marketing"),
        ("email-marketing", "Email Marketing", "marketing"),
        ("google-analytics", "Google Analytics", "marketing"),
        ("copywriting", "Copywriting", "marketing"),
        ("sales", "Sales", "marketing"),
        ("b2b-sales", "B2B Sales", "marketing"),
        ("api-design", "API Design", "engineering"),
        ("rest-api", "REST APIs", "engineering"),
        ("graphql", "GraphQL", "engineering"),
        ("microservices", "Microservices", "engineering"),
        ("system-design", "System Design", "engineering"),
        ("testing", "Testing / QA", "engineering"),
        ("security", "Cybersecurity", "engineering"),
        ("mobile-dev", "Mobile Development", "engineering"),
        ("web-dev", "Web Development", "engineering"),
        ("blockchain", "Blockchain", "engineering"),
    ]
    Skill.objects.bulk_create(
        [Skill(slug=s, name=n, category=c) for s, n, c in skills],
        ignore_conflicts=True,
    )


def reverse_seed(apps, schema_editor):
    Skill = apps.get_model("common", "Skill")
    Skill.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_seed_languages"),
    ]

    operations = [
        migrations.RunPython(seed_skills, reverse_seed),
    ]
