# Generated by Django 5.2.12 on 2026-03-20 17:26

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """Assign unique UUID tokens to all existing interviews."""
    Interview = apps.get_model("interviews", "Interview")
    for interview in Interview.objects.all():
        interview.interview_token = uuid.uuid4()
        interview.save(update_fields=["interview_token"])


def update_old_statuses(apps, schema_editor):
    """Migrate old statuses to new ones."""
    Interview = apps.get_model("interviews", "Interview")
    Interview.objects.filter(status="scheduled").update(status="pending")
    Interview.objects.filter(status="no_show").update(status="expired")

    Application = apps.get_model("applications", "Application")
    Application.objects.filter(status="interview_scheduled").update(status="applied")


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='interview',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='interview',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
        # Step 1: Add interview_token without unique constraint
        migrations.AddField(
            model_name='interview',
            name='interview_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Step 2: Populate unique tokens for existing rows
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # Step 3: Now make it unique and non-null
        migrations.AlterField(
            model_name='interview',
            name='interview_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='screening_mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('meet', 'Meet')], default='meet', max_length=10),
        ),
        migrations.AddField(
            model_name='interview',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewintegrityflag',
            name='flag_type',
            field=models.CharField(choices=[('face_not_visible', 'Face Not Visible'), ('multiple_faces', 'Multiple Faces'), ('gaze_deviation', 'Gaze Deviation'), ('audio_anomaly', 'Audio Anomaly'), ('cv_inconsistency', 'CV Inconsistency'), ('suspicious_timing', 'Suspicious Timing')], max_length=30),
        ),
        # Step 4: Migrate old statuses
        migrations.RunPython(update_old_statuses, migrations.RunPython.noop),
    ]
