# Generated by Django 5.2.12 on 2026-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_two_step_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
