# Generated by Django 5.2.12 on 2026-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0005_add_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="channel",
            field=models.CharField(choices=[("web", "Web"), ("telegram", "Telegram")], default="web", max_length=10),
        ),
    ]
