# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0008_alter_interview_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewscore",
            name="evidence",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
