# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0009_interviewscore_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="decision_support",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
