/**
 * ISO 3166-1 country list with English and Russian names.
 * Used for country autocomplete inputs.
 */
export interface Country {
  code: string
  name: string
  nameRu?: string
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', nameRu: 'Афганистан' },
  { code: 'AL', name: 'Albania', nameRu: 'Албания' },
  { code: 'DZ', name: 'Algeria', nameRu: 'Алжир' },
  { code: 'AD', name: 'Andorra', nameRu: 'Андорра' },
  { code: 'AO', name: 'Angola', nameRu: 'Ангола' },
  { code: 'AG', name: 'Antigua and Barbuda', nameRu: 'Антигуа и Барбуда' },
  { code: 'AR', name: 'Argentina', nameRu: 'Аргентина' },
  { code: 'AM', name: 'Armenia', nameRu: 'Армения' },
  { code: 'AU', name: 'Australia', nameRu: 'Австралия' },
  { code: 'AT', name: 'Austria', nameRu: 'Австрия' },
  { code: 'AZ', name: 'Azerbaijan', nameRu: 'Азербайджан' },
  { code: 'BS', name: 'Bahamas', nameRu: 'Багамы' },
  { code: 'BH', name: 'Bahrain', nameRu: 'Бахрейн' },
  { code: 'BD', name: 'Bangladesh', nameRu: 'Бангладеш' },
  { code: 'BB', name: 'Barbados', nameRu: 'Барбадос' },
  { code: 'BY', name: 'Belarus', nameRu: 'Беларусь' },
  { code: 'BE', name: 'Belgium', nameRu: 'Бельгия' },
  { code: 'BZ', name: 'Belize', nameRu: 'Белиз' },
  { code: 'BJ', name: 'Benin', nameRu: 'Бенин' },
  { code: 'BT', name: 'Bhutan', nameRu: 'Бутан' },
  { code: 'BO', name: 'Bolivia', nameRu: 'Боливия' },
  { code: 'BA', name: 'Bosnia and Herzegovina', nameRu: 'Босния и Герцеговина' },
  { code: 'BW', name: 'Botswana', nameRu: 'Ботсвана' },
  { code: 'BR', name: 'Brazil', nameRu: 'Бразилия' },
  { code: 'BN', name: 'Brunei', nameRu: 'Бруней' },
  { code: 'BG', name: 'Bulgaria', nameRu: 'Болгария' },
  { code: 'BF', name: 'Burkina Faso', nameRu: 'Буркина-Фасо' },
  { code: 'BI', name: 'Burundi', nameRu: 'Бурунди' },
  { code: 'KH', name: 'Cambodia', nameRu: 'Камбоджа' },
  { code: 'CM', name: 'Cameroon', nameRu: 'Камерун' },
  { code: 'CA', name: 'Canada', nameRu: 'Канада' },
  { code: 'CV', name: 'Cape Verde', nameRu: 'Кабо-Верде' },
  { code: 'CF', name: 'Central African Republic', nameRu: 'ЦАР' },
  { code: 'TD', name: 'Chad', nameRu: 'Чад' },
  { code: 'CL', name: 'Chile', nameRu: 'Чили' },
  { code: 'CN', name: 'China', nameRu: 'Китай' },
  { code: 'CO', name: 'Colombia', nameRu: 'Колумбия' },
  { code: 'KM', name: 'Comoros', nameRu: 'Коморы' },
  { code: 'CG', name: 'Congo', nameRu: 'Конго' },
  { code: 'CD', name: 'Congo (DRC)', nameRu: 'ДР Конго' },
  { code: 'CR', name: 'Costa Rica', nameRu: 'Коста-Рика' },
  { code: 'CI', name: "Côte d'Ivoire", nameRu: 'Кот-д’Ивуар' },
  { code: 'HR', name: 'Croatia', nameRu: 'Хорватия' },
  { code: 'CU', name: 'Cuba', nameRu: 'Куба' },
  { code: 'CY', name: 'Cyprus', nameRu: 'Кипр' },
  { code: 'CZ', name: 'Czech Republic', nameRu: 'Чехия' },
  { code: 'DK', name: 'Denmark', nameRu: 'Дания' },
  { code: 'DJ', name: 'Djibouti', nameRu: 'Джибути' },
  { code: 'DM', name: 'Dominica', nameRu: 'Доминика' },
  { code: 'DO', name: 'Dominican Republic', nameRu: 'Доминиканская Республика' },
  { code: 'EC', name: 'Ecuador', nameRu: 'Эквадор' },
  { code: 'EG', name: 'Egypt', nameRu: 'Египет' },
  { code: 'SV', name: 'El Salvador', nameRu: 'Сальвадор' },
  { code: 'GQ', name: 'Equatorial Guinea', nameRu: 'Экваториальная Гвинея' },
  { code: 'ER', name: 'Eritrea', nameRu: 'Эритрея' },
  { code: 'EE', name: 'Estonia', nameRu: 'Эстония' },
  { code: 'SZ', name: 'Eswatini', nameRu: 'Эсватини' },
  { code: 'ET', name: 'Ethiopia', nameRu: 'Эфиопия' },
  { code: 'FJ', name: 'Fiji', nameRu: 'Фиджи' },
  { code: 'FI', name: 'Finland', nameRu: 'Финляндия' },
  { code: 'FR', name: 'France', nameRu: 'Франция' },
  { code: 'GA', name: 'Gabon', nameRu: 'Габон' },
  { code: 'GM', name: 'Gambia', nameRu: 'Гамбия' },
  { code: 'GE', name: 'Georgia', nameRu: 'Грузия' },
  { code: 'DE', name: 'Germany', nameRu: 'Германия' },
  { code: 'GH', name: 'Ghana', nameRu: 'Гана' },
  { code: 'GR', name: 'Greece', nameRu: 'Греция' },
  { code: 'GD', name: 'Grenada', nameRu: 'Гренада' },
  { code: 'GT', name: 'Guatemala', nameRu: 'Гватемала' },
  { code: 'GN', name: 'Guinea', nameRu: 'Гвинея' },
  { code: 'GW', name: 'Guinea-Bissau', nameRu: 'Гвинея-Бисау' },
  { code: 'GY', name: 'Guyana', nameRu: 'Гайана' },
  { code: 'HT', name: 'Haiti', nameRu: 'Гаити' },
  { code: 'HN', name: 'Honduras', nameRu: 'Гондурас' },
  { code: 'HU', name: 'Hungary', nameRu: 'Венгрия' },
  { code: 'IS', name: 'Iceland', nameRu: 'Исландия' },
  { code: 'IN', name: 'India', nameRu: 'Индия' },
  { code: 'ID', name: 'Indonesia', nameRu: 'Индонезия' },
  { code: 'IR', name: 'Iran', nameRu: 'Иран' },
  { code: 'IQ', name: 'Iraq', nameRu: 'Ирак' },
  { code: 'IE', name: 'Ireland', nameRu: 'Ирландия' },
  { code: 'IL', name: 'Israel', nameRu: 'Израиль' },
  { code: 'IT', name: 'Italy', nameRu: 'Италия' },
  { code: 'JM', name: 'Jamaica', nameRu: 'Ямайка' },
  { code: 'JP', name: 'Japan', nameRu: 'Япония' },
  { code: 'JO', name: 'Jordan', nameRu: 'Иордания' },
  { code: 'KZ', name: 'Kazakhstan', nameRu: 'Казахстан' },
  { code: 'KE', name: 'Kenya', nameRu: 'Кения' },
  { code: 'KI', name: 'Kiribati', nameRu: 'Кирибати' },
  { code: 'KW', name: 'Kuwait', nameRu: 'Кувейт' },
  { code: 'KG', name: 'Kyrgyzstan', nameRu: 'Кыргызстан' },
  { code: 'LA', name: 'Laos', nameRu: 'Лаос' },
  { code: 'LV', name: 'Latvia', nameRu: 'Латвия' },
  { code: 'LB', name: 'Lebanon', nameRu: 'Ливан' },
  { code: 'LS', name: 'Lesotho', nameRu: 'Лесото' },
  { code: 'LR', name: 'Liberia', nameRu: 'Либерия' },
  { code: 'LY', name: 'Libya', nameRu: 'Ливия' },
  { code: 'LI', name: 'Liechtenstein', nameRu: 'Лихтенштейн' },
  { code: 'LT', name: 'Lithuania', nameRu: 'Литва' },
  { code: 'LU', name: 'Luxembourg', nameRu: 'Люксембург' },
  { code: 'MG', name: 'Madagascar', nameRu: 'Мадагаскар' },
  { code: 'MW', name: 'Malawi', nameRu: 'Малави' },
  { code: 'MY', name: 'Malaysia', nameRu: 'Малайзия' },
  { code: 'MV', name: 'Maldives', nameRu: 'Мальдивы' },
  { code: 'ML', name: 'Mali', nameRu: 'Мали' },
  { code: 'MT', name: 'Malta', nameRu: 'Мальта' },
  { code: 'MH', name: 'Marshall Islands', nameRu: 'Маршалловы Острова' },
  { code: 'MR', name: 'Mauritania', nameRu: 'Мавритания' },
  { code: 'MU', name: 'Mauritius', nameRu: 'Маврикий' },
  { code: 'MX', name: 'Mexico', nameRu: 'Мексика' },
  { code: 'FM', name: 'Micronesia', nameRu: 'Микронезия' },
  { code: 'MD', name: 'Moldova', nameRu: 'Молдова' },
  { code: 'MC', name: 'Monaco', nameRu: 'Монако' },
  { code: 'MN', name: 'Mongolia', nameRu: 'Монголия' },
  { code: 'ME', name: 'Montenegro', nameRu: 'Черногория' },
  { code: 'MA', name: 'Morocco', nameRu: 'Марокко' },
  { code: 'MZ', name: 'Mozambique', nameRu: 'Мозамбик' },
  { code: 'MM', name: 'Myanmar', nameRu: 'Мьянма' },
  { code: 'NA', name: 'Namibia', nameRu: 'Намибия' },
  { code: 'NR', name: 'Nauru', nameRu: 'Науру' },
  { code: 'NP', name: 'Nepal', nameRu: 'Непал' },
  { code: 'NL', name: 'Netherlands', nameRu: 'Нидерланды' },
  { code: 'NZ', name: 'New Zealand', nameRu: 'Новая Зеландия' },
  { code: 'NI', name: 'Nicaragua', nameRu: 'Никарагуа' },
  { code: 'NE', name: 'Niger', nameRu: 'Нигер' },
  { code: 'NG', name: 'Nigeria', nameRu: 'Нигерия' },
  { code: 'KP', name: 'North Korea', nameRu: 'КНДР' },
  { code: 'MK', name: 'North Macedonia', nameRu: 'Северная Македония' },
  { code: 'NO', name: 'Norway', nameRu: 'Норвегия' },
  { code: 'OM', name: 'Oman', nameRu: 'Оман' },
  { code: 'PK', name: 'Pakistan', nameRu: 'Пакистан' },
  { code: 'PW', name: 'Palau', nameRu: 'Палау' },
  { code: 'PS', name: 'Palestine', nameRu: 'Палестина' },
  { code: 'PA', name: 'Panama', nameRu: 'Панама' },
  { code: 'PG', name: 'Papua New Guinea', nameRu: 'Папуа — Новая Гвинея' },
  { code: 'PY', name: 'Paraguay', nameRu: 'Парагвай' },
  { code: 'PE', name: 'Peru', nameRu: 'Перу' },
  { code: 'PH', name: 'Philippines', nameRu: 'Филиппины' },
  { code: 'PL', name: 'Poland', nameRu: 'Польша' },
  { code: 'PT', name: 'Portugal', nameRu: 'Португалия' },
  { code: 'QA', name: 'Qatar', nameRu: 'Катар' },
  { code: 'RO', name: 'Romania', nameRu: 'Румыния' },
  { code: 'RU', name: 'Russia', nameRu: 'Россия' },
  { code: 'RW', name: 'Rwanda', nameRu: 'Руанда' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nameRu: 'Сент-Китс и Невис' },
  { code: 'LC', name: 'Saint Lucia', nameRu: 'Сент-Люсия' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', nameRu: 'Сент-Винсент и Гренадины' },
  { code: 'WS', name: 'Samoa', nameRu: 'Самоа' },
  { code: 'SM', name: 'San Marino', nameRu: 'Сан-Марино' },
  { code: 'ST', name: 'São Tomé and Príncipe', nameRu: 'Сан-Томе и Принсипи' },
  { code: 'SA', name: 'Saudi Arabia', nameRu: 'Саудовская Аравия' },
  { code: 'SN', name: 'Senegal', nameRu: 'Сенегал' },
  { code: 'RS', name: 'Serbia', nameRu: 'Сербия' },
  { code: 'SC', name: 'Seychelles', nameRu: 'Сейшелы' },
  { code: 'SL', name: 'Sierra Leone', nameRu: 'Сьерра-Леоне' },
  { code: 'SG', name: 'Singapore', nameRu: 'Сингапур' },
  { code: 'SK', name: 'Slovakia', nameRu: 'Словакия' },
  { code: 'SI', name: 'Slovenia', nameRu: 'Словения' },
  { code: 'SB', name: 'Solomon Islands', nameRu: 'Соломоновы Острова' },
  { code: 'SO', name: 'Somalia', nameRu: 'Сомали' },
  { code: 'ZA', name: 'South Africa', nameRu: 'ЮАР' },
  { code: 'KR', name: 'South Korea', nameRu: 'Южная Корея' },
  { code: 'SS', name: 'South Sudan', nameRu: 'Южный Судан' },
  { code: 'ES', name: 'Spain', nameRu: 'Испания' },
  { code: 'LK', name: 'Sri Lanka', nameRu: 'Шри-Ланка' },
  { code: 'SD', name: 'Sudan', nameRu: 'Судан' },
  { code: 'SR', name: 'Suriname', nameRu: 'Суринам' },
  { code: 'SE', name: 'Sweden', nameRu: 'Швеция' },
  { code: 'CH', name: 'Switzerland', nameRu: 'Швейцария' },
  { code: 'SY', name: 'Syria', nameRu: 'Сирия' },
  { code: 'TW', name: 'Taiwan', nameRu: 'Тайвань' },
  { code: 'TJ', name: 'Tajikistan', nameRu: 'Таджикистан' },
  { code: 'TZ', name: 'Tanzania', nameRu: 'Танзания' },
  { code: 'TH', name: 'Thailand', nameRu: 'Таиланд' },
  { code: 'TL', name: 'Timor-Leste', nameRu: 'Восточный Тимор' },
  { code: 'TG', name: 'Togo', nameRu: 'Того' },
  { code: 'TO', name: 'Tonga', nameRu: 'Тонга' },
  { code: 'TT', name: 'Trinidad and Tobago', nameRu: 'Тринидад и Тобаго' },
  { code: 'TN', name: 'Tunisia', nameRu: 'Тунис' },
  { code: 'TR', name: 'Turkey', nameRu: 'Турция' },
  { code: 'TM', name: 'Turkmenistan', nameRu: 'Туркменистан' },
  { code: 'TV', name: 'Tuvalu', nameRu: 'Тувалу' },
  { code: 'UG', name: 'Uganda', nameRu: 'Уганда' },
  { code: 'UA', name: 'Ukraine', nameRu: 'Украина' },
  { code: 'AE', name: 'United Arab Emirates', nameRu: 'ОАЭ' },
  { code: 'GB', name: 'United Kingdom', nameRu: 'Великобритания' },
  { code: 'US', name: 'United States', nameRu: 'США' },
  { code: 'UY', name: 'Uruguay', nameRu: 'Уругвай' },
  { code: 'UZ', name: 'Uzbekistan', nameRu: 'Узбекистан' },
  { code: 'VU', name: 'Vanuatu', nameRu: 'Вануату' },
  { code: 'VA', name: 'Vatican City', nameRu: 'Ватикан' },
  { code: 'VE', name: 'Venezuela', nameRu: 'Венесуэла' },
  { code: 'VN', name: 'Vietnam', nameRu: 'Вьетнам' },
  { code: 'YE', name: 'Yemen', nameRu: 'Йемен' },
  { code: 'ZM', name: 'Zambia', nameRu: 'Замбия' },
  { code: 'ZW', name: 'Zimbabwe', nameRu: 'Зимбабве' },
]

/**
 * Returns the display name for a country based on the current locale.
 * Falls back to English if a Russian translation is missing.
 */
export function countryDisplayName(country: Country, locale: string): string {
  if (locale === 'ru' && country.nameRu) return country.nameRu
  return country.name
}

export function resolveCountryDisplayName(
  countryCode: string | null | undefined,
  locale: string,
): string {
  const normalizedCode = countryCode?.trim().toUpperCase()

  if (!normalizedCode) return ''

  const country = COUNTRIES.find((item) => item.code === normalizedCode)
  return country ? countryDisplayName(country, locale) : countryCode?.trim() ?? ''
}
