export const ROUTE_NAMES = {
  LOGIN: 'login',
  REGISTER: 'register',
  VERIFY_EMAIL: 'verify-email',
  DASHBOARD: 'dashboard',
  VACANCY_LIST: 'vacancy-list',
  VACANCY_CREATE: 'vacancy-create',
  VACANCY_DETAIL: 'vacancy-detail',
  JOB_BOARD: 'job-board',
  JOB_DETAIL: 'job-detail',
  JOB_SHARE: 'job-share',
  JOB_APPLY: 'job-apply',
  MY_APPLICATIONS: 'my-applications',
  MY_APPLICATION_DETAIL: 'my-application-detail',
  VACANCY_CANDIDATES: 'vacancy-candidates',
  CANDIDATE_DETAIL: 'candidate-detail',
  INTERVIEW_LIST: 'interview-list',
  INTERVIEW_DETAIL: 'interview-detail',
  CANDIDATE_SCHEDULE: 'candidate-schedule',
  CANDIDATE_INTERVIEW: 'candidate-interview',
  INTERVIEW_CONFIRMATION: 'interview-confirmation',
  NOTIFICATIONS: 'notifications',
} as const
