# Generated by Django 5.2.12 on 2026-03-24 19:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_company_industries_m2m"),
        ("common", "0008_seed_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("headline", models.CharField(blank=True, default="", max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, default="", max_length=500)),
                ("github_url", models.URLField(blank=True, default="", max_length=500)),
                ("website_url", models.URLField(blank=True, default="", max_length=500)),
                ("desired_salary_min", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("desired_salary_max", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("desired_salary_currency", models.CharField(default="USD", max_length=3)),
                (
                    "desired_employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_open_to_work", models.BooleanField(default=True)),
                ("cv_pdf_file", models.CharField(blank=True, default="", max_length=500)),
                ("cv_pdf_template", models.CharField(default="classic", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skills", models.ManyToManyField(blank=True, related_name="candidate_profiles", to="common.skill")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(blank=True, default="", max_length=255)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_url", models.URLField(blank=True, default="", max_length=500)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="accounts.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(blank=True, default="", max_length=255)),
                ("field_of_study", models.CharField(blank=True, default="", max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "education_level",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="common.educationlevel"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="accounts.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="accounts.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_current", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CandidateLanguage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper Intermediate"),
                            ("advanced", "Advanced"),
                            ("native", "Native"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="common.language")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="accounts.candidateprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("profile", "language"), name="unique_candidate_language")
                ],
            },
        ),
    ]
