# Generated by Django 5.2.12 on 2026-03-24 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidate_profile_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cv_pdf_file',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cv_pdf_template',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My CV', max_length=255)),
                ('template', models.CharField(default='classic', max_length=50)),
                ('file', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts.candidateprofile')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
