# Generated by Django 5.2.12 on 2026-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_add_share_token_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="desired_salary_negotiable",
            field=models.BooleanField(default=False),
        ),
    ]
