# Generated by Django 5.2.12 on 2026-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_salary_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
