# Generated by Django 5.2.13 on 2026-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_alter_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("ru", "Russian"),
                    ("uz", "Uzbek"),
                    ("kk", "Kazakh"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("uk", "Ukrainian"),
                ],
                default="en",
                max_length=5,
            ),
        ),
    ]
