# Generated by Codex on 2026-05-20

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=Q(telegram_id__isnull=False, role__in=["admin", "hr"]),
                fields=["telegram_id"],
                name="unique_hr_admin_telegram_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=Q(telegram_id__isnull=False, role="candidate"),
                fields=["telegram_id"],
                name="unique_candidate_telegram_id",
            ),
        ),
    ]
