# Generated by Codex on 2026-05-20

from django.db import migrations, models


def backfill_active_mode(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role__in=["admin", "hr"]).update(active_mode="hr")
    User.objects.filter(role="candidate").update(active_mode="candidate")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_scope_telegram_id_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_mode",
            field=models.CharField(
                choices=[("hr", "HR"), ("candidate", "Candidate")],
                default="candidate",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_active_mode, migrations.RunPython.noop),
    ]
