# Generated by Codex on 2026-05-16

import uuid

from django.db import migrations, models


def populate_hiring_manager_tokens(apps, _schema_editor):
    application_model = apps.get_model("applications", "Application")
    for application in application_model.objects.filter(hiring_manager_token__isnull=True):
        application.hiring_manager_token = uuid.uuid4()
        application.save(update_fields=["hiring_manager_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0008_backfill_profile_resume_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="hiring_manager_token",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_hiring_manager_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="application",
            name="hiring_manager_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
