# Generated by Codex on 2026-05-16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0009_hiring_manager_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiringManagerFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_role", models.CharField(blank=True, default="", max_length=255)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[("advance", "Advance"), ("maybe", "Maybe"), ("reject", "Reject")],
                        max_length=20,
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiring_manager_feedback",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
