# Generated by Codex on 2026-05-16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0010_hiringmanagerfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("share_link_rotated", "Share Link Rotated"),
                            ("hiring_manager_feedback", "Hiring Manager Feedback"),
                        ],
                        max_length=50,
                    ),
                ),
                ("actor_name", models.CharField(blank=True, default="", max_length=255)),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="applications.application",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
