# Generated by Codex on 2026-05-17

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_hr_candidates(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    HRCandidate = apps.get_model("applications", "HRCandidate")

    applications = (
        Application.objects.filter(candidate_email__gt="", is_deleted=False)
        .select_related("candidate", "vacancy", "vacancy__company")
        .order_by("created_at")
    )
    for application in applications:
        account_owner_id = application.vacancy.company.account_owner_id
        normalized_email = application.candidate_email.strip().lower()
        if not normalized_email:
            continue

        candidate, created = HRCandidate.objects.get_or_create(
            account_owner_id=account_owner_id,
            candidate_email_normalized=normalized_email,
            defaults={
                "candidate_id": application.candidate_id,
                "candidate_name": application.candidate_name,
                "candidate_email": application.candidate_email,
                "candidate_phone": application.candidate_phone,
                "latest_application_id": application.id,
                "first_seen_at": application.created_at,
                "last_activity_at": application.updated_at,
            },
        )
        if created:
            continue

        update_fields = []
        if application.created_at < candidate.first_seen_at:
            candidate.first_seen_at = application.created_at
            update_fields.append("first_seen_at")
        if application.updated_at >= candidate.last_activity_at:
            candidate.candidate_id = application.candidate_id or candidate.candidate_id
            candidate.candidate_name = application.candidate_name or candidate.candidate_name
            candidate.candidate_email = application.candidate_email
            candidate.candidate_phone = application.candidate_phone or candidate.candidate_phone
            candidate.latest_application_id = application.id
            candidate.last_activity_at = application.updated_at
            update_fields.extend(
                [
                    "candidate",
                    "candidate_name",
                    "candidate_email",
                    "candidate_phone",
                    "latest_application",
                    "last_activity_at",
                ]
            )
        if update_fields:
            candidate.save(update_fields=list(dict.fromkeys(update_fields)))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_alter_user_language"),
        ("applications", "0011_applicationevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRCandidate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_name", models.CharField(max_length=255)),
                ("candidate_email", models.EmailField(max_length=254)),
                ("candidate_email_normalized", models.CharField(max_length=254)),
                ("candidate_phone", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                ("first_seen_at", models.DateTimeField()),
                ("last_activity_at", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "account_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_candidates",
                        to="accounts.user",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_candidate_records",
                        to="accounts.user",
                    ),
                ),
                (
                    "latest_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hrcandidate",
            index=models.Index(
                fields=["account_owner", "candidate_email_normalized"],
                name="applicatio_account_494f7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrcandidate",
            index=models.Index(
                fields=["account_owner", "last_activity_at"],
                name="applicatio_account_540a3e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="hrcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("account_owner", "candidate_email_normalized"),
                name="unique_active_hr_candidate_email_per_account",
            ),
        ),
        migrations.RunPython(backfill_hr_candidates, migrations.RunPython.noop),
    ]
