# Generated by Django 5.2.13 on 2026-04-24 23:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_rework_invitation_to_account'),
        ('vacancies', '0018_shift_criteria_order_to_one_based'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedVacancySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('hh_ru', 'hh.ru'), ('hh_uz', 'hh.uz'), ('telegram', 'Telegram')], max_length=20)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_vacancy_sources', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_vacancy_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedVacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('employment_type', models.CharField(blank=True, default='', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('expired', 'Expired'), ('closed', 'Closed'), ('unknown', 'Unknown'), ('duplicate', 'Duplicate'), ('imported', 'Imported')], default='unknown', max_length=20)),
                ('actuality_reason', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('imported_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_sources', to='vacancies.vacancy')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='job_parser.parsedvacancysource')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parsedvacancysource',
            index=models.Index(fields=['company', 'source_type'], name='job_parser__company_60c99a_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedvacancysource',
            index=models.Index(fields=['is_active', 'last_synced_at'], name='job_parser__is_acti_7361e7_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedvacancy',
            index=models.Index(fields=['source', 'status'], name='job_parser__source__64460a_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedvacancy',
            index=models.Index(fields=['status', 'last_seen_at'], name='job_parser__status_eda53d_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedvacancy',
            index=models.Index(fields=['fingerprint'], name='job_parser__fingerp_0fcab9_idx'),
        ),
        migrations.AddConstraint(
            model_name='parsedvacancy',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_parsed_vacancy_per_source'),
        ),
    ]
