# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedvacancysource",
            name="sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="parsedvacancysource",
            name="sync_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsedvacancysource",
            name="sync_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsedvacancysource",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("running", "Running"),
                    ("stopping", "Stopping"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="parsedvacancysource",
            name="sync_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
