# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_parser", "0002_source_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsedvacancysource",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
