# Generated by Django 5.2.13 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_parser", "0003_disable_parser_sources_by_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedvacancysource",
            name="last_seen_external_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="parsedvacancysource",
            name="last_seen_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="parsedvacancysource",
            index=models.Index(
                fields=["source_type", "is_active", "last_synced_at"],
                name="job_parser_source__8f5a6f_idx",
            ),
        ),
    ]
